import Head from 'next/head'
import Navbar from '../components/Navbar'
import AOS from 'aos'
import 'aos/dist/aos.css'
import { useEffect } from 'react'
import { FaHtml5, FaCss3Alt, FaJsSquare, FaReact, FaGithub, FaBootstrap, FaNode, FaPython } from 'react-icons/fa'
import { GrArchlinux, GrUbuntu, GrGraphQl } from "react-icons/gr";
import { DiJqueryLogo, DiDjango } from "react-icons/di";
import { SiMysql, SiMongodb } from "react-icons/si";

export default function Home() {

  useEffect(() => {
    AOS.init({ duration: 2000 });
  }, [])

  return (
    <div className='scroll-smooth bg-gray-900'>
      <Head>
        <title>John Doe Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className='flex justify-center items-center flex-col text-white'>

        <section data-aos='fade-up' data-aos-easing="ease-in-out" className='snap-normal h-screen flex flex-col justify-center items-center'>
          <h1 className='uppercase text-2xl font-bold tracking-widest mb-1'><span className='text-red-500'>Hello</span>, I'm John Doe</h1>  
          <h6 className='text-sm mb-3 opacity-80'>FRONT-END DEVELOPER</h6>

          <div className='flex flex-row justify-center items-center text-sm space-x-2'>
            <button className='py-1 px-2 bg-red-600 rounded-sm hover:brightness-200 drop-shadow-lg font-bold'>
              RESUME
            </button>
            <button className='py-1 px-2 bg-red-600 rounded-sm hover:brightness-200 drop-shadow-lg font-bold'>
              SERVICES
            </button>
          </div>

        </section>

        <section id='about' data-aos='fade-up' className='snap-normal h-screen flex justify-center items-center text-2xl font-bold'>
          <div className='max-w-screen-lg mx-auto px-4 text-center'>
            <h1 className='mb-4 uppercase text-green-400'>About Me</h1>
            <p className='font-normal md:text-lg text-sm'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </div>
        </section>

        <section data-aos='fade-up' className='snap-normal h-screen flex flex-col justify-center items-center font-bold'>
          
          <h1 className='mb-6 text-4xl'>MY SKILLS</h1>  

          <div className='text-5xl flex flex-col space-y-4'>

            <div className='flex flex-wrap justify-center items-center space-x-2 mb-2'>
              <FaHtml5 className='text-orange-400' />

              <FaCss3Alt className='text-blue-400' />

              <FaJsSquare className='text-yellow-400' />

              <DiJqueryLogo className='text-cyan-400' />

              <FaBootstrap className='text-violet-500' />

              <FaReact className='text-cyan-400' />

              <DiDjango className='text-green-500' />

              <FaNode className='text-gray-300' />   
            </div>        

            <div className='flex justify-center items-center flex-col mb-2'>
              <h1 className='text-xl uppercase'>Operating System</h1>
              <div className='flex flex-wrap space-x-2'>
                <GrArchlinux className='text-cyan-500' /> 
                <GrUbuntu className='text-orange-400' />  
              </div>
            </div>  

            <div className='flex justify-center items-center flex-col'>
              <h1 className='text-2xl'>Database</h1>
              <div className='flex flex-wrap space-x-2'>
                <SiMysql className='text-blue-400' /> 
                <GrGraphQl className='text-pink-500' /> 
                <SiMongodb className='text-green-400' /> 
              </div>
            </div>

          </div>
        </section>

        <section id='services' data-aos='fade-up' className='snap-normal h-screen flex flex-col justify-center items-center'>
          <h1 className='text-2xl font-bold'>SERVICES</h1>  

          <div className='max-w-screen-lg mx-auto px-4 mt-6'>
            <div className='flex flex-col p-4 rounded-md bg-gray-800'>
              <h1 className='text-2xl'>WordPress Development</h1>
              <div className='flex space-x-2 '>
                <div>
                  <img src='/wordpress.jpg' className='w-full h-full' />
                </div>

                <div>  
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                  </p>
                </div>
              </div>
              
            </div>

          </div>

        </section>
        
        <section id='contact' data-aos='fade-up' className='snap-normal h-screen flex justify-center items-center text-2xl'>

          <div className='max-w-screen-lg mx-auto px-4'>

            <h1 className='mb-4 uppercase font-bold text-green-400'>Contact John Doe</h1>
            <h5 className='mb-6'>Let's discuss your next project.</h5>

            <form>
              <div className='mb-4 flex flex-wrap items-center md:justify-between justify-center md:space-x-4 space-x-0'>
                <div className=''>
                  <label for='txtname'>Name</label>
                  <input for='txtname' type='text' placeholder='Name' className='w-full' />
                </div>
                <div className=''>
                  <label for='txtemail'>Email Address</label>
                  <input id='txtemail' type='text' placeholder='Email Address' className='w-full' />
                </div>
              </div>

              <div className='mb-4'>
                <label for='txtsubject'>Subject</label>
                <input id='txtsubject' type='text' placeholder='Subject' className='w-full' />
              </div>

              <div className=''>
                <label for='txtmessage'>Message</label>
                <textarea for='txtmessage' placeholder='Message' className='w-full' />
              </div>

            </form>
          </div>

        </section>

      </main>

      <footer>

      </footer>
      
    </div>
  )
}
